POST http://localhost:8000/auth/login
Content-type: application/json

{
    "username" : "hieuhieu",
    "password" : "hieuhieu"
}

###
GET http://localhost:8000/auth/logout
Content-type: application/json
{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoiYW5odHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQzMzgxMjUsImV4cCI6MTY0NDMzODE1NX0.BFW5wDVhw9uSnga-VlN-d1zn_IqSgD_em6DS6fR89cI"
}

###
GET  http://localhost:8000/auth/user
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoiYW5odHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQzMzc3NjEsImV4cCI6MTY0NDMzNzc5MX0.gMeO7aNkaJev9xrii3cs4vYAkinHf6sOHoogH9HOCq0


###
POST http://localhost:8000/admin/newQuestion
content-type: application/json

{
  "content": "test question 4?",
}

###
POST   http://localhost:8000/auth/token
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoiYW5odHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQzMDg0NzMsImV4cCI6MTY0NDM5NDg3M30.65Fd6BMwCXmZD-jpkccwmuoVm184pwrogzvuVHjDo2A"
}