POST http://localhost:8000/auth/login
Content-type: application/json

{
    "username" : "anhtuan",
    "password" : "anhtuan"
}

###
GET http://localhost:8000/auth/logout
Content-type: application/json
{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoidHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQ5MzE3NjcsImV4cCI6MTY0NTAxODE2N30.YVDNSj9wYQGkbE4bWrj3zzF3m6KFwmBY7qyfVIgh3ns"
}

###
GET  http://localhost:8000/user/getRandomQuestions
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoiYW5odHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQzMzc3NjEsImV4cCI6MTY0NDMzNzc5MX0.gMeO7aNkaJev9xrii3cs4vYAkinHf6sOHoogH9HOCq0


###
POST http://localhost:8000/admin/newQuestion
content-type: application/json

{
  "content": "test question 4?",
}

###
POST   http://localhost:8000/user/token
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoiYW5odHVhbiIsImVtYWlsIjoidHVhbkBnbWFpbC5jb20iLCJpYXQiOjE2NDQ5MzE3NjcsImV4cCI6MTY0NTAxODE2N30.YVDNSj9wYQGkbE4bWrj3zzF3m6KFwmBY7qyfVIgh3ns"
}